image: php:7.1.1

clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y unzip git
          - git subtree push --prefix=backend https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_BACKEND_APP_NAME.git master
          - git subtree push --prefix=frontend https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_FRONTEND_APP_NAME.git master
