version: 2.1

orbs:
  # react: 'thefrontside/react@dev:alpha'
  heroku: circleci/heroku@0.0.6

executors:
  default:
    description: |
      Node 10 runtime environment
    docker:
    - image: circleci/node:10

jobs:
  install:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - checkout
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - run: yarn install
      - persist_to_workspace:
          paths:
            - project
          root: ~/
      - save_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
          paths:
          - ~/project/node_modules
  lint:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn install
      - run: mkdir -p reports/eslint
      - run: yarn eslint ./frontend/src/**/*.{ts,tsx} --config ./frontend/.eslintrc.json --ignore-path ./frontend/.eslintignore --format junit --output-file ../reports/eslint/eslint.xml
      - store_test_results:
          path: reports/eslint
      - store_artifacts:
          path: reports/eslint
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master

workflows:
  push:
    jobs:
      - install
      - lint:
          requires:
            - install
      - deploy:
          requires:
            - lint