module.exports = {
  // Get Auth User
  AUTH_GET_USER: 'AUTH_GET_USER',
  // User Login
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  // User Register
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_FAILED: 'AUTH_REGISTER_FAILED',
  // User Logout
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  // Period
  GET_ACTIVE_PERIOD: 'GET_ACTIVE_PERIOD',
};
