module.exports = {
  // Get Auth User
  AUTH_GET_USER: 'AUTH_GET_USER',
  // User Login
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  // User Register
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_FAILED: 'AUTH_REGISTER_FAILED',
  // User Logout
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  // Period
  GET_ACTIVE_PERIOD: 'GET_ACTIVE_PERIOD',
  GET_PERIOD: 'GET_PERIOD',
  GET_ALL_PERIODS: 'GET_ALL_PERIODS',
  CREATE_PERIOD: 'CREATE_PERIOD',
  UPDATE_PERIOD: 'UPDATE_PERIOD',
  DELETE_PERIOD: 'DELETE_PERIOD',

  // Module
  GET_MODULE: 'GET_MODULE',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',

  // User
  GET_USER: 'GET_USER',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Senpai
  GET_SENPAI_MODULES: 'GET_SENPAI_MODULES',

  // Settings
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
};
